spring.application.name=portofolio-arya

# Basic JDBC Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/portofolio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Development reload settings
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.jpa.defer-datasource-initialization=true
